name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: master

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
